# DOCKER ENV

export WALLET_SERVICE_NAME="be-wallet"
export WALLET_SERVICE_IMAGE_NAME="wallet-service"
export WALLET_SERVICE_IMAGE_VERSION="0.0.1"
export NETWORK_NAME="bridge-signature"

# DOCKER IMAGE UPDATE

if docker image inspect $WALLET_SERVICE_IMAGE_NAME:$WALLET_SERVICE_IMAGE_VERSION &> /dev/null; then
    docker image rm -f $WALLET_SERVICE_IMAGE_NAME:$WALLET_SERVICE_IMAGE_VERSION
fi

docker build -t $WALLET_SERVICE_IMAGE_NAME:$WALLET_SERVICE_IMAGE_VERSION .

# DOCKER SERVICE RUN

if [ "$(docker ps -aq -f name=$WALLET_SERVICE_NAME)" ]; then
    docker rm -f $WALLET_SERVICE_NAME
fi

docker run -d \
--network $NETWORK_NAME \
--name $WALLET_SERVICE_NAME \
-p $WALLET_SERVICE_PORT:$WALLET_SERVICE_PORT \
$WALLET_SERVICE_IMAGE_NAME:$WALLET_SERVICE_IMAGE_VERSION